"""Operation -> queryId table (all values verified live 2026-09-19)."""

QIDS = {
    # ledger reads (GET)
    "Following": "-Mn4uN7C-vxXBwUKtSwS6A", "PinnedTimelines": "1C9qXYjxcujNpyJWE6tAeg",
    "CreatorStudioTabBarItemQuery": "1KZj_GRTxmPaSrk8jIb1Yw",
    "isEligibleForVoButtonUpsellQuery": "BuWF9hiwmUyFdGo3J4DqbA",
    "BlueVerifiedFollowers": "DWeIe6l1rsZMqHPbbWXtig",
    "FetchScheduledTweets": "H2elmT2R9DLhWoo0DZFNkA",
    "useStoryTopicQuery": "I3V_Tt32aTZdw7cBdKUJbg",
    "ProfileTeamRoster": "I5ALHyuvPb6h7soVmbcq9g",
    "NflScoresSidebarFollow": "JR_EpH80gwgFyOBOreLBZw",    "UserByScreenName": "KybxDj9RrADIITXlGG8kpw",
    "NotificationsTimeline": "MSUPE4KwuxyghDO60Bv5uQ",  # user-captured 2026-09-20
    "FetchDraftTweets": "L9RqKWmAWxK6vGtR3Qdsxw",
    "QuickPromoteEligibility": "LtpCXh66W-uXh7u7XSRA8Q",
    "ProfileSeasonSchedule": "M946jrb9CchmjVYMukJ6RQ",
    "UsersVerifiedAvatars": "O9O_O1iF0QffoOBjB2OGIQ",
    "getAltTextPromptPreference": "PFIxTk8owMoZgiMccP0r4g",
    "SidebarUserRecommendations": "XFGj2pdlasiM3FndUe1PrQ",
    "UserOriginalsTimeline": "Yr8749ieoUptxRqQv766Fw",
    "Followers": "fVGYs5W9kNUuoUrZwYZQpQ",  # POST only (GET 404s)
    "ProfileSpotlightsQuery": "mzoqrVGwk-YTSGME1dRfXQ",
    "ViewerBadgeCounts": "q4Npr1-FYRWyXsRzPckwEA",
    "DataSaverMode": "xF6sXnKJfS2AOylzxRjf6A",
    "ExploreSidebar": "zJF1HRGpRjCStcTNm5aekA",
    # ledger writes (POST)
    "HomeTimeline": "og4a4SdSF3WiQkkwaPCdPg",
    "FavoriteTweet": "lI07N6Otwv1PhnEgXILM7A",
    "CreateRetweet": "mbRO74GrOvSfRcJnlMapnQ",
    "CreateTweet": "GYdIGqVWfZNho79bQ2XDoA",  # txn-id REQUIRED
    "usePremiumPaywallOnLoadMutation": "F6gikc1Bwzry7oHMrdrYzg",
    "PutClientEducationFlag": "IjQ-egg0uPkY11NyPMfRMQ",
    # discovered in JS, verified live
    "Viewer": "9t128XgFic52jPUEkJMf6w",
    "TweetResultByRestId": "Xl0tsHf4AzflMRjbw9e70A",
    "TweetDetail": "zoF7_t363wZyzylk-BLfZQ",
    "UserTweets": "jeAA-59Y9FL7FmjgBNIVPw",
    "UserRepliesTimeline": "xz348nziCm96wndJ1S0MUQ",
    "UserMedia": "TwLiEVUhRjjjKVc98IT0TQ",
    "Likes": "XHn_Tw60c6pi0n3DGhpwiA",
    "UserRepostsTimeline": "CnNg1YiKG7bRgi-RoIfKsw",
    "UserVideoTimeline": "8FjnVm2ZmIymF6l1Tw2fBQ",
    "UserHighlightsTweets": "TtovDhtuqVtzzfZ9fpztlw",
    "UserArticlesTweets": "ic9_Nc9wg4whcOEBiWAP4w",
    "UserPhotoTimeline": "-7Kl-CfOGgXpmvSvNxuPpA",
    "UserTweetsAndReplies": "wI-ubAWfScnG6odLK4XgCg",  # POST only
    "UserSuperFollowTweets": "6SjR3fvrAJwMXjnYF-0KEQ",
    "UserPromotedTweets": "K8KVrFEj0ec0WnOZOtTpaA",
    "UserPromotableTweets": "bwNtu6M5zSf94E7TmbrRIA",
    "UserByRestId": "IdmRdjYxIGI39Hdwkwo5cQ",
    "UsersByRestIds": "BuQFwM7wpHl00cfHL-r0rA",  # POST only
    "UsersByScreenNames": "8G9O4pAkWTXNv3XQuOGVrw",
    "SearchTimeline": "auLkqtmHqYEpRvflfvLhyQ",  # POST only
    "ExplorePage": "7JBlImZfRkZIptknshoqCA",
    "SupportedLanguages": "fZ5uZVeledO5SAseKnmTUg",
    "GetUserClaims": "aQ-b88K_Lp7dgHX53MqNQQ",
    "UserPreferences": "xFxU-O8hEYe74ovNVU74jA",
    "UserSessionsList": "vJ-XatpmQSG8bDch8-t9Jw",
    "Upsells": "Sg3BvwapuCMIjLJ7LGPhMA",
    "PinnableTimelines": "XUpSmUE_n6ez-U_SdC7G7g",
    "MutedAccounts": "doSy_eEELN6ol2addK5OfA",
    "BlockedAccountsAll": "VlsRzrlUBsLKHvQdoYdSGw",
    "BlockedAccountsImported": "S05B7hxH_1XPxdMiKT-VlQ",
    "ModeratedTimeline": "kO0Oq6PcLpvQacRyW3LIPw",
    "ConnectTabTimeline": "2a5nvYPVhrgXZqTUg8O5ZA",
    "BookmarkSearchTimeline": "rbwiGBFqb93lmG7mw_OYZQ",
    "ListSearchTimeline": "i4096Pm5N66WDAdjumVLrQ",
    "SimilarPosts": "pnl_SipPG1I4d2CBGCEgQw",
    "TrendRelevantUsers": "Av5yDFt1dtyBu2vhvvTA1g",
    "TrendHistory": "2e9kT9dZau_UsQy29Ssj8Q",
    "FinanceSearchTags": "4VTsYZ3r4xYW9S0Rys5G0A",
    "GetUsernameAvailabilityAndSuggestions": "1bMz-9lPrmIXrhFmXntTHw",  # POST
    "ProfileUserPhoneState": "5kUWP8C1hcd6omvg6HXXTQ",
    "SuperFollowers": "4A1krY2Xn7uTA4tGOM6Gzw",
    "UserCreatorSubscriptions": "NteGelNq-3jzn3gbc7fyvA",
    "UserCreatorSubscribers": "ZKWe719CjFmlxZM95aw_yQ",
    "FollowersYouKnow": "hEiuVHcQAxCsfSE9aL2e_g",
    "MediaTabVideoMixer": "fGRGW6Se0cRPDbyIK3wjTA",
    "BakeryQuery": "pROR-yRiBVsEjJyHt3fvhg",
    "GlobalCommunitiesPostSearchTimeline": "tbfwt3lMoSiVODtsBmEFGQ",
    "GlobalCommunitiesLatestPostSearchTimeline": "tKfhQuBk1YpT2yhpMng0Gw",
    "TVHomeMixer": "Mxc2_ki1khctdccHe5LN6A",
    "PaymentsUsersTypeahead": "dlHFEO5q9vveDgITz9zELg",
    # mutations, all verified live (pairs restore state)
    "UnfavoriteTweet": "ZYKSe-w7KEslx3JhSIk5LA",
    "DeleteRetweet": "ZyZigVsNiFO6v1dEks1eWg",  # source_tweet_id = ORIGINAL id
    "CreateBookmark": "aoDbu3RHznuiSkQ9aNM67Q",  # txn-id REQUIRED
    "DeleteBookmark": "Wlmlj2-xzyS1GN3a6cj-mQ",
    "DownvoteTweet": "Iu4kUV4vd_iHMupiHPPrAQ",
    "UndoDownvoteTweet": "yqhcbdyy59k-FCwOysvvGQ",
    "DeleteTweet": "nxpZCY2K-I6QoFHAHeojFQ",
    "PinTweet": "VIHsNu89pK-kW35JpHq7Xw",
    "UnpinTweet": "BhKei844ypCyLYCg0nwigw",
    "dmBlockUser": "IYw9u1KEhrS-t-BXsau4Uw",
    "dmUnblockUser": "Krbs6Nak_o7liWQwfV1jOQ",
    "AddContentDisclosure": "D1nwFlsu_qHsX92YzoRaaA",
    "AuthenticatePeriscope": "r7VUmxbfqNkx7uwjgONSNw",
    "CommunityMemberRelationshipTypeahead": "6YgvBKI7c3YZ9d7zKKojng",
    "CommunityUserRelationshipTypeahead": "MOKE3VjNMJ7BVsWdNkv32g",
    "ConversationControlChange": "57WYJNnWH0vM3Ip_gm8B2g",
    "ConversationControlDelete": "OoMO_aSZ1ZXjegeamF9QmA",
    "CreateHighlight": "7jEc7ECTTDcNaqsMhjTxXg",
    "CreateNoteTweet": "u-Vsy3HZId2j10nbdqMI0A",
    "DeleteContentDisclosure": "YeIV-eqGwEZXDtYaDsJz2Q",
    "DeleteHighlight": "ea-VVDSLIEYNY2_2aPg3Uw",
    "DisableVerifiedPhoneLabel": "g2m0pAOamawNtVIfjXNMJg",
    "DmNsfwMediaFilterUpdate": "of_N6O33zfyD4qsFJMYFxA",
    "EnableVerifiedPhoneLabel": "C3RJFfMsb_KcEytpKmRRkw",
    "GenericTimelineById": "6KKcBTcCsVtXvAx4aFDzRQ",
    "ModerateTweet": "pjFnHGVqCjTcZol0xcBJjw",
    "PinTimeline": "ZMYcJPUQ0QIAyWekMdAuDw",
    "ProfileFilter": "O6BaAhZzuUp7_TTTynMF2g",
    "RemoveFollower": "QpNfg0kpPRfjROQ_9eOLXA",
    "SharingAudiospacesListeningDataWithFollowersUpdate": "5h0kNbk3ii97rmfY6CdgAA",
    "TweetResultsByRestIds": "mQnBPxNdkMLfhXINDDYUSg",
    "UnmentionUserFromConversation": "xVW9j3OqoBRY9d6_2OONEg",
    "UnmoderateTweet": "pVSyu6PA57TLvIE4nN2tsA",
    "UnpinTimeline": "_uu6eZuimGwywEa4qtZxZA",
    "UnpinTweet": "BhKei844ypCyLYCg0nwigw",
    "UpdatePinnedTimelines": "AtN-0mKI3fXXmxzYYk1Wqw",
    "UrtFixtures": "Jw90Znej2ooqJH0gx1voEA",
    "UserBusinessProfileTeamTimeline": "v_oniRKLdCZ__sqG-6yTqQ",
    "WriteDataSaverPreferences": "H03etWvZGz41YASxAU2YPg",
    "timelinesFeedback": "vfVbgvTPTQ-dF_PQ5lD1WQ",
    "updateAltTextPromptPreference": "aQKrduk_DA46XfOQDkcEng",
}
